# Generated by Django 4.2.29 on 2026-03-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterysubmission',
            name='city',
            field=models.CharField(default='Город отсутствует', max_length=100, verbose_name='Город сдачи'),
        ),
    ]
